server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      default-filters:
#        - TokenRelay=
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/**
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: spring
#            client-id: client
#            client-secret: secret
#            scope: openid, profile
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:9000/auth/callback
#        provider:
#          spring:
#            issuer-uri: http://localhost:9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true