spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  security: 
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080
